name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install flask
          pip install flask-wtf
          pip install flask-sqlalchemy
          pip install email-validator

      - name: Test all tests
        run: python -m unittest discover tests
